default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: food_api_development


test:
  <<: *default
  database: food_api_test

production:
  database: food_api_production
  username: food_api
  password: <%= ENV['FOOD_API_DATABASE_PASSWORD'] %>
